version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./src:/app/src"
    ports:
      - "3000:3000"
    depends_on:
    - mongo
  mongo:
    command: mongod
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none
